# Generated by Django 4.0 on 2021-12-24 18:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_genre_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='watchlist',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.profile'),
        ),
    ]
