# Generated by Django 4.0 on 2021-12-24 18:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_watchlist_profile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='program',
            old_name='thumbclick',
            new_name='thumbclip',
        ),
    ]
