# Generated by Django 4.0 on 2022-01-07 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_rename_thumbclick_program_thumbclip'),
    ]

    operations = [
        migrations.AddField(
            model_name='program',
            name='seasons',
            field=models.IntegerField(default=0),
        ),
    ]
