# Generated by Django 4.0 on 2022-01-08 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_program_seasons'),
    ]

    operations = [
        migrations.AlterField(
            model_name='program',
            name='runtime',
            field=models.IntegerField(default=0),
        ),
    ]
